enum QuestionTypeEnum {
    NAO_IDENTIFICADO = 'NAO_IDENTIFICADO',
    CIDADANIA_E_MEIO_AMBIENTE = 'CIDADANIA_E_MEIO_AMBIENTE',
    DIRECAO_DEFENSIVA = 'DIRECAO_DEFENSIVA', 
    LEGISLACAO = 'LEGISLACAO', 
    PRIMEIROS_SOCORROS = 'PRIMEIROS_SOCORROS',
    MECANICA_BASICA = 'MECANICA_BASICA',
    PLACAS_DE_TRANSITO = 'PLACAS_DE_TRANSITO',
};

export default QuestionTypeEnum